#!/usr/bin/env bash

# Manually set PATH to use the namaz environment
export PATH="/home/mendel/.conda/envs/namaz/bin:$PATH"
export GI_TYPELIB_PATH=$CONDA_PREFIX/lib/girepository-1.0
export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH


conda activate namaz
#change to the folder
cd /home/linaro/namaz/
sudo git pull

# Run Python application
# Attempt to run the first Python script
python /home/linaro/namaz/app2.py
