#!/usr/bash

sudo apt-get update

sudo chmod +x /home/mendel/namaz/baslat

sudo chown mendel:mendel /home/mendel/.config/
sudo chmod 755 /home/mendel/.config/
[ -w /home/mendel/.config/matplotlib ] && echo "Writable" || echo "Not Writable"

